import { ChakraProvider } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'ress'
import '../global.css'
import Layout from "./_components/layout/Layout";
import { createTable } from "@/server/dynamo-db";
import AuthProvider from "./_components/auth/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

let isStarted = false;
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  if (!isStarted) {
    isStarted = true
    await createTable()
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider cssVarsRoot="body">
          <AuthProvider>
            <Layout>
              {children}
            </Layout>
          </AuthProvider>

        </ChakraProvider>
      </body>
    </html>
  );
}
