version: '3.8'

services:

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  minio:
    image: minio/minio:latest
    volumes:
      - ./minio/data:/data
      - ./minio/export:/export
      - ./minio/config:/root/.minio
      - ./minio/policies:/policies
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9001 root password;
      /usr/bin/mc rm -r --force myminio/blogs;
      /usr/bin/mc mb myminio/blogs;
      /usr/bin/mc policy download myminio/blogs;
      exit 0;
      "

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: document-blog-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=yourStrongPassword
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    # command:
    #   - eland_import_hub_model --url "http://elasticsearch:9200"  --hub-model-id cl-tohoku bert-base-japanese-v2 --task-type text_embedding --start

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: document-blog-kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local:latest
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    environment:
      AWS_ACCESS_KEY_ID: "dummy"
      AWS_SECRET_ACCESS_KEY: "dummy"
      AWS_DEFAULT_REGION: "ap-northeast-1"
    volumes:
      - dynamodb-data:/data
    ports:
      - 8000:8000
  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local

networks:
  dynamodb-network:
    driver: bridge

volumes:
  postgres-data:
  minio:
  es_data:
    driver: local
  dynamodb-data:
    name: dynamodb-data




